<?php

/**
 * This is the model base class for the table "seo_model_meta".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SeoModelMeta".
 * This code was improve iReevo Team
 * Columns in table "seo_model_meta" available as properties of the model,
 * followed by relations of table "seo_model_meta" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 * @property string $content
 * @property integer $seo_model_id
 *
 * @property SeoModel $seoModel
 * @property ImageARBehavior $imageAR
 */
abstract class BaseSeoModelMeta extends I18NInTableAdapter
{

    public static function model($className = __CLASS__)
    {
        return parent::model($className);
    }

    public static function label($n = 1)
    {
        return Yii::t('SeoModelMeta', 'SeoModelMeta|SeoModelMetas', $n);
    }

    public static function representingColumn()
    {
        return 'name';
    }

    public function tableName()
    {
        return 'seo_model_meta';
    }

    public function i18nAttributes()
    {
        return array();
    }

    public function rules()
    {
        return array(
            array('name, content, seo_model_id', 'required'),
            array('seo_model_id', 'numerical', 'integerOnly' => true),
            array('name', 'length', 'max' => 255),
            array('id, name, content, seo_model_id', 'safe', 'on' => 'search'),
            array('SeoModel', 'safe'),
        );
    }

    public function relations()
    {
        return array(
            'seoModel' => array(self::BELONGS_TO, 'SeoModel', 'seo_model_id'),
        );
    }

    public function pivotModels()
    {
        return array();
    }

    public function attributeLabels()
    {
        return array(
            'id' => Yii::t('SeoModelMeta', 'id'),
            'name' => Yii::t('SeoModelMeta', 'name'),
            'content' => Yii::t('SeoModelMeta', 'content'),
            'seo_model_id' => Yii::t('SeoModelMeta', 'seo_model_id'),

        );
    }

    public function search()
    {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('name', $this->name, true);
        $criteria->compare('content', $this->content, true);
        $criteria->compare('seo_model_id', $this->seo_model_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
}