<?php

/**
 * This is the model base class for the table "general_tracking_codes".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GeneralTrackingCodes".
 * This code was improve iReevo Team
 * Columns in table "general_tracking_codes" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $source_code
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseGeneralTrackingCodes extends GxActiveRecord {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'general_tracking_codes';
	}

	public static function label($n = 1) {
		return self::model()->t_model('GeneralTrackingCodes|GeneralTrackingCodes', $n);
	}

	public static function representingColumn() {
		return 'source_code';
	}

	public function rules() {
		return array(
			array('id, source_code', 'required'),
			array('id', 'length', 'max'=>50),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, source_code', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'source_code' => $this->t_label('Source code'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('source_code', $this->source_code, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}