<?php

/**
 * This is the model base class for the table "article".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Article".
 * This code was improve iReevo Team
 * Columns in table "article" available as properties of the model,
 * followed by relations of table "article" available as properties of the model.
 *
 * @property string $id
 * @property string $title
 * @property string $author
 * @property string $date
 * @property string $large_description
 * @property string $short_description
 * @property string $large_image
 * @property string $thumb_image
 * @property string $youtube_video
 * @property string $category
 *
 * @property ArticleCategory $category0
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseArticle extends I18NInTableAdapter {
    
/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    public $recipeImg1;
    public $recipeImg2;
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
            'seo' => array(
                            'class' => 'seo.components.SeoModelBehavior',
                        ),
                

                                '_large_image' => array(
                    'class' => 'ImageARBehavior',
                    'attribute' => 'recipeImg1', // this must exist
                    'extension' => 'jpg,gif,png', // possible extensions, comma separated
                    'prefix' => 'img1_',
                    'relativeWebRootFolder' => '/images/Article',
                    'formats' => array(
                    // create a thumbnail for used in the view datails
                    'thumb' => array(
                    'suffix' => '_thumb',
                    'process' => array('resize' => array(50, 50)),
                    ),
                    'normal' => array(
                    'suffix' => '_normal',

                                        'process' => array('resize' => array(1036,575, 1)),
                                        ),
                    // and override the default :
                    ),

                    'defaultName' => 'default', // when no file is associated, this one is used
                            // defaultName need to exist in the relativeWebRootFolder path, and prefixed by prefix,
                            // and with one of the possible extensions. if multiple formats are used, a default file must exist
                            // for each format. Name is constructed like this :
                            //     {prefix}{name of the default file}{suffix}{one of the extension}
                ),
                                '_thumb_image' => array(
                    'class' => 'ImageARBehavior',
                    'attribute' => 'recipeImg2', // this must exist
                    'extension' => 'jpg,gif,png', // possible extensions, comma separated
                    'prefix' => 'img2_',
                    'relativeWebRootFolder' => '/images/Article',
                    'formats' => array(
                    // create a thumbnail for used in the view datails
                    'thumb' => array(
                    'suffix' => '_thumb',
                    'process' => array('resize' => array(50, 50)),
                    ),
                    'normal' => array(
                    'suffix' => '_normal',

                                        'process' => array('resize' => array(381,272, 1)),
                                        ),
                    // and override the default :
                    ),

                    'defaultName' => 'default', // when no file is associated, this one is used
                            // defaultName need to exist in the relativeWebRootFolder path, and prefixed by prefix,
                            // and with one of the possible extensions. if multiple formats are used, a default file must exist
                            // for each format. Name is constructed like this :
                            //     {prefix}{name of the default file}{suffix}{one of the extension}
                ),
                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'article';
	}

	public static function label($n = 1) {
		return self::model()->t_model('Article|Articles', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

    public function i18nAttributes() {
        return array(
        'title', 'large_description', 'short_description', );
    }

	public function rules() {
		return array(
			array('id, title, large_description, short_description, thumb_image', 'required'),
//			array('seo_url_id', 'numerical', 'integerOnly'=>true),
			array('id, large_image, category', 'length', 'max'=>50),
			array('title, author, thumb_image, youtube_video', 'length', 'max'=>255),
			array('date', 'safe'),
			array('author, date, large_image, youtube_video, category', 'default', 'setOnEmpty' => true, 'value' => null),
			array('title, large_description, short_description', 'i18n.validators.I18NValidator', 'validate' => 'required'),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/
    array('recipeImg1', 'file', 'on'=>'insert', 'allowEmpty'=>true, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg1', 'file', 'on'=>'update', 'allowEmpty'=>true, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg1', 'safe'),
    array('recipeImg2', 'file', 'on'=>'insert', 'allowEmpty'=>false, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg2', 'file', 'on'=>'update', 'allowEmpty'=>true, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg2', 'safe'),


			array('id, title, author, date, large_description, short_description, large_image, thumb_image, youtube_video, category', 'safe', 'on'=>'search'),
//                    array('seo_url, seo_title, seo_keywords, seo_description', 'safe'),
//            array('seo_url, seo_title', 'required'),
            array('ArticleCategory, SeoUrl', 'safe'),
		);
	}

	public function relations() {
		return array(
			'category0' => array(self::BELONGS_TO, 'ArticleCategory', 'category'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'title' => $this->t_label('Title'),
			'author' => $this->t_label('Autor'),
			'date' => $this->t_label('Date'),
			'large_description' => $this->t_label('Description'),
			'short_description' => $this->t_label('Short description'),
			'large_image' => $this->t_label('Large Image Alt'),
			'thumb_image' => $this->t_label('Thumbnail image Alt'),
			'youtube_video' => $this->t_label('Youtube video'),
			'category' => $this->t_label('Category'),
						    'recipeImg1' => $this->t_label('Large Image'),
    'recipeImg2' => $this->t_label('Thumbnail image'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('author', $this->author, true);
		$criteria->compare('date', $this->date, true);
		$criteria->compare('large_description', $this->large_description, true);
		$criteria->compare('short_description', $this->short_description, true);
		$criteria->compare('large_image', $this->large_image, true);
		$criteria->compare('thumb_image', $this->thumb_image, true);
		$criteria->compare('youtube_video', $this->youtube_video, true);
		$criteria->compare('category', $this->category);

        $criteria->order = 'date desc';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}