<?php

/**
 * This is the model base class for the table "newsletter".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Newsletter".
 * This code was improve iReevo Team
 * Columns in table "newsletter" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $subscriber
 * @property string $created
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseNewsletter extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'newsletter';
	}

	public static function label($n = 1) {
		return self::model()->t_model('Newsletter|Newsletters', $n);
	}

	public static function representingColumn() {
		return 'subscriber';
	}

    public function i18nAttributes() {
        return array(
        );
    }

	public function rules() {
		return array(
			array('id, subscriber', 'required'),
			array('id', 'length', 'max'=>50),
			array('subscriber', 'length', 'max'=>250),
			array('created', 'safe'),
			array('created', 'default', 'setOnEmpty' => true, 'value' => null),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, subscriber, created', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'subscriber' => $this->t_label('Subscriber'),
			'created' => $this->t_label('Created'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('subscriber', $this->subscriber, true);
		$criteria->compare('created', $this->created, true);
		$criteria->order = 'created desc';

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}