<?php

/**
 * This is the model base class for the table "navigation_menu".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NavigationMenu".
 * This code was improve iReevo Team
 * Columns in table "navigation_menu" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $home
 * @property string $buy
 * @property string $rent
 * @property string $contact_us
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseNavigationMenu extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'navigation_menu';
	}

	public static function label($n = 1) {
		return self::model()->t_model('NavigationMenu|NavigationMenus', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

    public function i18nAttributes() {
        return array(
        'home', 'buy', 'rent', 'contact_us', );
    }

	public function rules() {
		return array(
			array('id', 'required'),
			array('id', 'length', 'max'=>50),
			array('home, buy, rent, contact_us', 'length', 'max'=>255),
			array('home, buy, rent, contact_us', 'default', 'setOnEmpty' => true, 'value' => null),
			array('home, buy, rent, contact_us', 'i18n.validators.I18NValidator', 'validate' => 'required'),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, home, buy, rent, contact_us', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'home' => $this->t_label('Home'),
			'buy' => $this->t_label('Buy'),
			'rent' => $this->t_label('Rent'),
			'contact_us' => $this->t_label('Contact us'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('home', $this->home, true);
		$criteria->compare('buy', $this->buy, true);
		$criteria->compare('rent', $this->rent, true);
		$criteria->compare('contact_us', $this->contact_us, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}