<?php

/**
 * This is the model base class for the table "company_info".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CompanyInfo".
 * This code was improve iReevo Team
 * Columns in table "company_info" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $company_logo
 * @property string $company_name
 * @property string $main_phone
 * @property string $second_phone
 * @property string $email
 * @property string $postal_address
 * @property string $web_address
 * @property double $map_longitude
 * @property double $map_latitude
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseCompanyInfo extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    public $recipeImg1;
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                                '_company_logo' => array(
                    'class' => 'ImageARBehavior',
                    'attribute' => 'recipeImg1', // this must exist
                    'extension' => 'jpg,gif,png', // possible extensions, comma separated
                    'prefix' => 'img1_',
                    'relativeWebRootFolder' => '/images/CompanyInfo',
                    'formats' => array(
                    // create a thumbnail for used in the view datails
                    'thumb' => array(
                    'suffix' => '_thumb',
                    'process' => array('resize' => array(50, 50)),
                    ),
                    'normal' => array(
                    'suffix' => '_normal',

                                        'process' => array('resize' => array(127,39, 1)),
                                        ),
                    // and override the default :
                    ),

                    'defaultName' => 'default', // when no file is associated, this one is used
                            // defaultName need to exist in the relativeWebRootFolder path, and prefixed by prefix,
                            // and with one of the possible extensions. if multiple formats are used, a default file must exist
                            // for each format. Name is constructed like this :
                            //     {prefix}{name of the default file}{suffix}{one of the extension}
                ),
                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'map_longitude,map_latitude',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'company_info';
	}

	public static function label($n = 1) {
		return self::model()->t_model('CompanyInfo|CompanyInfos', $n);
	}

	public static function representingColumn() {
		return 'company_name';
	}

    public function i18nAttributes() {
        return array(
        );
    }

	public function rules() {
		return array(
			array('id, company_name, main_phone, email, map_longitude, map_latitude', 'required'),
			array('map_longitude, map_latitude', 'numerical', 'numberPattern' => "/{$this->currency->pathern}/"),
			array('id', 'length', 'max'=>50),
			array('company_logo, company_name, main_phone, second_phone, email, web_address', 'length', 'max'=>255),
			array('postal_address', 'safe'),
			array('company_logo, second_phone, postal_address, web_address', 'default', 'setOnEmpty' => true, 'value' => null),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/
    array('recipeImg1', 'file', 'on'=>'insert', 'allowEmpty'=>true, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg1', 'file', 'on'=>'update', 'allowEmpty'=>true, 'types'=>'jpg,jpeg,gif,png,JPG,GIF,JPEG,PNG', 'maxSize'=>1024*1024*6),
array('recipeImg1', 'safe'),


			array('id, company_logo, company_name, main_phone, second_phone, email, postal_address, web_address, map_longitude, map_latitude', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'company_logo' => $this->t_label('Logo Alt'),
			'company_name' => $this->t_label('Company name'),
			'main_phone' => $this->t_label('Main phone'),
			'second_phone' => $this->t_label('Second phone'),
			'email' => $this->t_label('Email'),
			'postal_address' => $this->t_label('Postal address'),
			'web_address' => $this->t_label('Web address'),
			'map_longitude' => $this->t_label('Map longitude'),
			'map_latitude' => $this->t_label('Map latitude'),
    'recipeImg1' => $this->t_label('Logo'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('company_logo', $this->company_logo, true);
		$criteria->compare('company_name', $this->company_name, true);
		$criteria->compare('main_phone', $this->main_phone, true);
		$criteria->compare('second_phone', $this->second_phone, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('postal_address', $this->postal_address, true);
		$criteria->compare('web_address', $this->web_address, true);
		$criteria->compare('map_longitude', $this->map_longitude);
		$criteria->compare('map_latitude', $this->map_latitude);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}