<?php

/**
 * This is the model base class for the table "buy_list_page_filter_config".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "BuyListPageFilterConfig".
 * This code was improve iReevo Team
 * Columns in table "buy_list_page_filter_config" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property double $first_price
 * @property double $last_price
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseBuyListPageFilterConfig extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'first_price,last_price',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'buy_list_page_filter_config';
	}

	public static function label($n = 1) {
		return self::model()->t_model('BuyListPageFilterConfig|BuyListPageFilterConfigs', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

    public function i18nAttributes() {
        return array(
        );
    }

	public function rules() {
		return array(
			array('id, first_price, last_price', 'required'),
			array('first_price, last_price', 'numerical', 'numberPattern' => "/{$this->currency->pathern}/"),
            array('first_price', 'compare', 'operator' => '<', 'compareAttribute' => 'last_price'),
			array('id', 'length', 'max'=>50),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, first_price, last_price', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'first_price' => $this->t_label('First price'),
			'last_price' => $this->t_label('Last price'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('first_price', $this->first_price);
		$criteria->compare('last_price', $this->last_price);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}