<?php

/**
 * This is the model base class for the table "footer_navigation_menu".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FooterNavigationMenu".
 * This code was improve iReevo Team
 * Columns in table "footer_navigation_menu" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $home
 * @property string $about_us
 * @property string $terms_conditions
 * @property string $blog
 * @property string $publish_properties
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseFooterNavigationMenu extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'footer_navigation_menu';
	}

	public static function label($n = 1) {
		return self::model()->t_model('FooterNavigationMenu|FooterNavigationMenus', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

    public function i18nAttributes() {
        return array(
        'home', 'about_us', 'terms_conditions', 'blog', 'publish_properties', );
    }

	public function rules() {
		return array(
			array('id', 'required'),
			array('id', 'length', 'max'=>50),
			array('home, about_us, terms_conditions, blog, publish_properties', 'length', 'max'=>255),
			array('home, about_us, terms_conditions, blog, publish_properties', 'default', 'setOnEmpty' => true, 'value' => null),
			array('home, about_us, terms_conditions, blog, publish_properties', 'i18n.validators.I18NValidator', 'validate' => 'required'),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, home, about_us, terms_conditions, blog, publish_properties', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'home' => $this->t_label('Home'),
			'about_us' => $this->t_label('About us text'),
			'terms_conditions' => $this->t_label('Terms & Conditions text'),
			'blog' => $this->t_label('Blog text'),
			'publish_properties' => $this->t_label('Publish your properties text'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('home', $this->home, true);
		$criteria->compare('about_us', $this->about_us, true);
		$criteria->compare('terms_conditions', $this->terms_conditions, true);
		$criteria->compare('blog', $this->blog, true);
		$criteria->compare('publish_properties', $this->publish_properties, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}