<?php

/**
 * This is the model base class for the table "contact_us_reason".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ContactUsReason".
 * This code was improve iReevo Team
 * Columns in table "contact_us_reason" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $title
 * @property integer $priority
 *
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseContactUsReason extends I18NInTableAdapter {

/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'contact_us_reason';
	}

	public static function label($n = 1) {
		return self::model()->t_model('ContactUsReason|ContactUsReasons', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

    public function i18nAttributes() {
        return array(
        'title', );
    }

	public function rules() {
		return array(
			array('id, title, priority', 'required'),
			array('priority', 'numerical', 'integerOnly'=>true),
			array('id', 'length', 'max'=>50),
			array('title', 'length', 'max'=>250),
			array('title', 'i18n.validators.I18NValidator', 'validate' => 'required'),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, title, priority', 'safe', 'on'=>'search'),
        		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'title' => $this->t_label('Title'),
			'priority' => $this->t_label('Priority'),

		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('priority', $this->priority);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}