<?php

/**
 * This is the model base class for the table "article_category".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ArticleCategory".
 * This code was improve iReevo Team
 * Columns in table "article_category" available as properties of the model,
 * followed by relations of table "article_category" available as properties of the model.
 *
 * @property string $id
 * @property string $title
 *
 * @property Article[] $articles
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BaseArticleCategory extends I18NInTableAdapter {
// many to many relationship
            public $Article;
    
/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'article_category';
	}

	public static function label($n = 1) {
		return self::model()->t_model('ArticleCategory|ArticleCategories', $n);
	}

	public static function representingColumn() {
		return 'title';
	}

    public function i18nAttributes() {
        return array(
        'title', );
    }

	public function rules() {
		return array(
			array('id, title', 'required'),
			array('id', 'length', 'max'=>50),
			array('title', 'length', 'max'=>255),
			array('title', 'i18n.validators.I18NValidator', 'validate' => 'required'),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/


			array('id, title', 'safe', 'on'=>'search'),
            array('Article', 'safe'),
		);
	}

	public function relations() {
		return array(
			'articles' => array(self::HAS_MANY, 'Article', 'category'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'title' => $this->t_label('Title'),
			
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('title_'.app()->language, $this->title, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}