<?php

/**
 * This is the model base class for the table "property_amenitie".
 * It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PropertyAmenitie".
 * This code was improve iReevo Team
 * Columns in table "property_amenitie" available as properties of the model,
 * followed by relations of table "property_amenitie" available as properties of the model.
 *
 * @property string $id
 * @property string $amenitie_id
 * @property string $property_id
 * @property integer $relevant
 *
 * @property Amenitie $amenitie
 * @property Property $property
 * @property Date2TimeBehavior $date2time
 * @property CurrencyBehavior $currency
 * @property ImageARBehavior $imageAR

 */
abstract class BasePropertyAmenitie extends I18NInTableAdapter {
// many to many relationship
            public $Amenitie;
            public $Property;
    
/* si tiene una imagen pa subir con ImageARBehavior, descomente la linea siguiente
// public $recipeImg;

    /**
    * Behaviors.
    * @return array
    */
    function behaviors() {
        return CMap::mergeArray(parent::behaviors(), array(
                

                

                                'files' => array(
                     'class'=>'application.modules.ycm.behaviors.FileBehavior',
                ),
                'date2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d',
                ),
                'datetime2time' => array(
                    'class' => 'ycm.behaviors.Date2TimeBehavior',
                    'attributes'=>'',
                    'format'=>'Y-m-d H:i:s',
                ),
                'currency' => array(
                    'class' => 'ycm.behaviors.CurrencyBehavior',
                    'attributes'=>'',
                ),
                            ));
    }


	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'property_amenitie';
	}

	public static function label($n = 1) {
		return self::model()->t_model('PropertyAmenitie|PropertyAmenities', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

    public function i18nAttributes() {
        return array(
        );
    }

	public function rules() {
		return array(

//            array('amenitie_id', 'UniqueAttributesValidator', 'with'=>'property_id'),
            array('amenitie_id+property_id', 'uniqueMultiColumnValidator'),

			array('id, amenitie_id, property_id', 'required'),
			array('relevant', 'boolean'),
			array('id, amenitie_id, property_id', 'length', 'max'=>50),
			array('relevant', 'default', 'setOnEmpty' => true, 'value' => null),

/* descomente las lineas siguientes si quiere subir una image con ImageARBehavior*/

//            array(['property_id', 'amenitie_id'], 'unique', 'targetAttribute' => ['property_id', 'amenitie_id']),

			array('id, amenitie_id, property_id, relevant', 'safe', 'on'=>'search'),
            array('Amenitie, Property', 'safe'),
		);
	}

	public function relations() {
		return array(
			'amenitie' => array(self::BELONGS_TO, 'Amenitie', 'amenitie_id'),
			'property' => array(self::BELONGS_TO, 'Property', 'property_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => $this->t_label('ID'),
			'amenitie_id' => $this->t_label('Amenity'),
			'property_id' => $this->t_label('Property'),
			'relevant' => $this->t_label('Relevant'),
						
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('amenitie_id', $this->amenitie_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('relevant', $this->relevant);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
            		));
	}
}